# Generated by Django 6.1 on 2026-08-24 04:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('classes', '0001_initial'),
        ('packages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_deducted', models.BooleanField(default=False)),
                ('checked_in_at', models.DateTimeField(auto_now_add=True)),
                ('class_offering', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='classes.classoffering')),
                ('package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkins', to='packages.package')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to='accounts.student')),
            ],
            options={
                'verbose_name': 'Asistencia',
                'verbose_name_plural': 'Asistencias',
                'ordering': ['-checked_in_at'],
            },
        ),
    ]
