# Generated by Django 6.1 on 2026-08-24 04:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('packages', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notif_type', models.CharField(choices=[('low_credit', 'Le queda 1 clase (correo al alumno)'), ('package_exhausted', 'Paquete agotado (alerta a recepción)'), ('package_expired', 'Paquete/mensualidad vencida (alerta a recepción)')], max_length=20)),
                ('channel', models.CharField(choices=[('email', 'Correo al alumno'), ('internal', 'Alerta interna (recepción)')], max_length=10)),
                ('message', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='packages.package')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='accounts.student')),
            ],
            options={
                'verbose_name': 'Notificación / alerta',
                'verbose_name_plural': 'Notificaciones / alertas',
                'ordering': ['-sent_at'],
            },
        ),
    ]
