# Generated by Django 6.1 on 2026-08-24 04:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('social', 'Social'), ('lineas', 'Líneas (artístico)')], max_length=10)),
                ('price', models.DecimalField(decimal_places=0, max_digits=10)),
                ('credit_count', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tipo de paquete',
                'verbose_name_plural': 'Tipos de paquete',
                'ordering': ['category', 'price'],
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_date', models.DateField(default=django.utils.timezone.localdate)),
                ('expires_at', models.DateField(editable=False)),
                ('credits_remaining', models.PositiveIntegerField(blank=True, null=True)),
                ('payment_method', models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia')], max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sold_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='accounts.student')),
                ('package_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='packages.packagetype')),
            ],
            options={
                'verbose_name': 'Paquete / mensualidad',
                'verbose_name_plural': 'Paquetes / mensualidades',
                'ordering': ['-purchase_date'],
            },
        ),
    ]
